### ISSUE TITLE
deformatter doesn't work correctly with nested inline blanks

### ISSUE THREAD

**Issue by unhammer** [SilentFlame/apertium#4]
As of 17e0b89916f7d64a238c49a22b42bbc9c209e58e it doesn't put the inline blank on `fiz` below:

    $ echo '<p>foo <b>bar fie <i>baz</i> fum</b> fiz</p>' |./deformatter
    [<p>]foo [{<b>}]bar fie [{<i><b>}]baz[] fum[] fiz[][</p>]

This should be

    [<p>]foo [{<b>}]bar fie [{<i><b>}]baz[{<b>}] fum[] fiz[</p>]

**Comment by SilentFlame** [comment]
commit 416f8f4216c7551f87f2c16c6d6e49fdb12f92f0 closed this issue.
